services:
    screen-saver:
        container_name: screen-saver
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5178:80"
        security_opt:
            - no-new-privileges:true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 30s
            timeout: 10s
            retries: 5